#!/bin/bash
#This file can be used with the Pintos Operating System to run tests while you are still coding and checking things.
#To do this add this file to your ~/bin directory and add the bin directory to your .bash_profile $PATH variable.
#Make sure to run bash before running checkPintos and also make sure to add the executable flag.
#Also make sure to edit line 2 so it goes to the src/threads directory of pintos.
# Created by Nickalas Porsch
cd ~/pintos/src/threads
while true
do
	make clean
	make check
	now=$(date +"%T")
	echo "Test Ran at: $now";
	sleep 5m
done
