#!/bin/bash

<<COMMENT
MIT License

Copyright (c) 2020 nwporsch

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

COMMENT


#This file can be used with the Pintos Operating System to run tests while you are still coding and checking things.
#To do this add this file to your ~/bin directory and add the bin directory to your .bash_profile $PATH variable.
#Make sure to run bash before running checkPintos and also make sure to add the executable flag.
#Also make sure to edit line 2 so it goes to the src/threads directory of pintos.
#Make sure to change cis520 to the correct folder for your pintos operating system.
if [[ $1 -eq "1" ]]
then
	cd ~/cis520/pintos/src/threads
elif [[ $1 -eq "2" ]
then
	cd ~/cis520/pintos/src/vm
else
	echo "Invalid Argument";
	exit 1
fi


while true
do
	if [ $1 -eq "3" ]] # Project 3 has to check if userprog and vm directories are correct.
	then
		cd ~/cis520/pintos/src/userprog
		make clean
		make check
		cd ~/cis520/pintos/src/vm
	fi
	
	make clean
	make check
	now=$(date +"%T")
	echo "Test Ran at: $now";
	sleep 5m
done
